application: hello-002
version: 1
runtime: java

system_properties:
  java.util.logging.config.file: WEB-INF/classes/logging.properties
  scalate.allowReload: false
  scalate.workdir: WEB-INF

resource_files:
  - include: /**.scaml
  - include: /**.ssp

handlers:
  - url: "*.scaml"
#    filter: org.fusesource.scalate.servlet.TemplateEngineFilter
    servlet: ya.TemplateEngineServlet
  - url: "*.ssp"
#    filter: org.fusesource.scalate.servlet.TemplateEngineFilter
    servlet: ya.TemplateEngineServlet

